id: PYSEC-0000-CVE-2024-27133
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:H/A:H
details: Insufficient sanitization in MLflow leads to XSS when running a recipe that
  uses an untrusted dataset. This issue leads to a client-side RCE when running the
  recipe in Jupyter Notebook. The vulnerability stems from lack of sanitization over
  dataset table fields.
affected:
- package:
    name: mlflow
    ecosystem: PyPI
    purl: pkg:pypi/mlflow
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 2.10.0
references:
- type: EVIDENCE
  url: https://research.jfrog.com/vulnerabilities/mlflow-untrusted-dataset-xss-jfsa-2024-000631932/
- type: FIX
  url: https://github.com/mlflow/mlflow/pull/10893
- type: REPORT
  url: https://github.com/mlflow/mlflow/pull/10893
- type: WEB
  url: https://research.jfrog.com/vulnerabilities/mlflow-untrusted-dataset-xss-jfsa-2024-000631932/
aliases:
- CVE-2024-27133
modified: "2025-01-22T13:46:56Z"
published: "2024-02-23T22:15:55Z"
